### ISSUE TITLE
only size-1 arrays can be converted to Python scalars

### ISSUE THREAD

**Issue by sayannath** [sayakpaul/E2E-Object-Detection-in-TFLite#2]
Running [this](https://github.com/sayakpaul/E2E-Object-Detection-in-TFLite/blob/master/Object_Detection_in_TFLite.ipynb) file to get the inference
![Screenshot 2021-11-02 at 2 12 20 PM](https://user-images.githubusercontent.com/41967348/139813693-fe2ca6c8-12e8-46be-a966-720603b737b2.png)

Any workaround for this?

**Comment by sayakpaul** [comment]
You probably need to ensure that your input to `int()` is a zero-rank array.
